/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import clasesBackground.ImagenFondo;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Document;
import com.itextpdf.text.Font;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Image;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.BaseFont;
import com.itextpdf.text.pdf.PdfContentByte;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.File;
import java.io.FileOutputStream;
import java.io.FileWriter;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;

public class fr_Generacion_Vale_Salida_Almacen extends javax.swing.JFrame {

    String NombreUsuario,Cantidad,Autorizada,Articulo,Fecha;
    public fr_Generacion_Vale_Salida_Almacen() {
        initComponents();
        dp_background_principal.setBorder(new ImagenFondo());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pn_encabezado = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        dp_background_principal = new javax.swing.JDesktopPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        pb_principal = new javax.swing.JPanel();
        pn_datos_bien_asignados = new javax.swing.JPanel();
        lb_no_inventario = new javax.swing.JLabel();
        tf_nombre_usuario = new javax.swing.JTextField();
        tf_cantidad = new javax.swing.JTextField();
        lb_no_serie = new javax.swing.JLabel();
        lb_descripcion = new javax.swing.JLabel();
        tf_autorizada = new javax.swing.JTextField();
        lb_marca = new javax.swing.JLabel();
        tf_articulo = new javax.swing.JTextField();
        lb_modelo = new javax.swing.JLabel();
        tf_fecha = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        pn_acciones = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Generación de Vales de Resguardo de Bienes");
        setPreferredSize(new java.awt.Dimension(1372, 836));

        pn_encabezado.setBackground(new java.awt.Color(255, 204, 204));
        pn_encabezado.setAlignmentX(0.0F);
        pn_encabezado.setAlignmentY(0.0F);
        pn_encabezado.setPreferredSize(new java.awt.Dimension(1576, 150));
        pn_encabezado.setRequestFocusEnabled(false);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/IEE_logo-iloveimg-resized.png"))); // NOI18N

        javax.swing.GroupLayout pn_encabezadoLayout = new javax.swing.GroupLayout(pn_encabezado);
        pn_encabezado.setLayout(pn_encabezadoLayout);
        pn_encabezadoLayout.setHorizontalGroup(
            pn_encabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_encabezadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(1366, Short.MAX_VALUE))
        );
        pn_encabezadoLayout.setVerticalGroup(
            pn_encabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_encabezadoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addContainerGap())
        );

        getContentPane().add(pn_encabezado, java.awt.BorderLayout.NORTH);

        dp_background_principal.setBackground(new java.awt.Color(153, 153, 255));

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        pb_principal.setBackground(new java.awt.Color(255, 153, 152));

        pn_datos_bien_asignados.setBackground(new java.awt.Color(255, 153, 153));
        pn_datos_bien_asignados.setLayout(new java.awt.GridBagLayout());

        lb_no_inventario.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lb_no_inventario.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lb_no_inventario.setText("Nombre de usuario");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        pn_datos_bien_asignados.add(lb_no_inventario, gridBagConstraints);

        tf_nombre_usuario.setMinimumSize(new java.awt.Dimension(150, 30));
        tf_nombre_usuario.setPreferredSize(new java.awt.Dimension(150, 30));
        tf_nombre_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_nombre_usuarioActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 271;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        pn_datos_bien_asignados.add(tf_nombre_usuario, gridBagConstraints);

        tf_cantidad.setMinimumSize(new java.awt.Dimension(150, 30));
        tf_cantidad.setPreferredSize(new java.awt.Dimension(150, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 271;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        pn_datos_bien_asignados.add(tf_cantidad, gridBagConstraints);

        lb_no_serie.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lb_no_serie.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lb_no_serie.setText("Cantidad");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        pn_datos_bien_asignados.add(lb_no_serie, gridBagConstraints);

        lb_descripcion.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lb_descripcion.setText("Autorizada");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        pn_datos_bien_asignados.add(lb_descripcion, gridBagConstraints);

        tf_autorizada.setMinimumSize(new java.awt.Dimension(150, 30));
        tf_autorizada.setPreferredSize(new java.awt.Dimension(150, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 271;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        pn_datos_bien_asignados.add(tf_autorizada, gridBagConstraints);

        lb_marca.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lb_marca.setText("Articulo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        pn_datos_bien_asignados.add(lb_marca, gridBagConstraints);

        tf_articulo.setMinimumSize(new java.awt.Dimension(150, 30));
        tf_articulo.setPreferredSize(new java.awt.Dimension(150, 30));
        tf_articulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_articuloActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 271;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        pn_datos_bien_asignados.add(tf_articulo, gridBagConstraints);

        lb_modelo.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lb_modelo.setText("Fecha");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        pn_datos_bien_asignados.add(lb_modelo, gridBagConstraints);

        tf_fecha.setMinimumSize(new java.awt.Dimension(150, 30));
        tf_fecha.setPreferredSize(new java.awt.Dimension(150, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 271;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        pn_datos_bien_asignados.add(tf_fecha, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel3.setText("Salida de almacén");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        pn_datos_bien_asignados.add(jLabel3, gridBagConstraints);

        jPanel2.setBackground(new java.awt.Color(255, 153, 153));

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel4.setText("Criterio:");

        jTextField2.setPreferredSize(new java.awt.Dimension(6, 30));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "No. Inventario", "No. Serie", "Descripción", "Marca", "Modelo", "Color" }));
        jComboBox2.setPreferredSize(new java.awt.Dimension(56, 30));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(138, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(jTable2);

        javax.swing.GroupLayout pb_principalLayout = new javax.swing.GroupLayout(pb_principal);
        pb_principal.setLayout(pb_principalLayout);
        pb_principalLayout.setHorizontalGroup(
            pb_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pb_principalLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(pb_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pn_datos_bien_asignados, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 634, Short.MAX_VALUE))
                .addGap(145, 145, 145))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pb_principalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(174, 174, 174))
        );
        pb_principalLayout.setVerticalGroup(
            pb_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pb_principalLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(pn_datos_bien_asignados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jScrollPane2.setViewportView(pb_principal);

        javax.swing.GroupLayout dp_background_principalLayout = new javax.swing.GroupLayout(dp_background_principal);
        dp_background_principal.setLayout(dp_background_principalLayout);
        dp_background_principalLayout.setHorizontalGroup(
            dp_background_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dp_background_principalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 762, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(804, Short.MAX_VALUE))
        );
        dp_background_principalLayout.setVerticalGroup(
            dp_background_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dp_background_principalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 602, Short.MAX_VALUE)
                .addContainerGap())
        );
        dp_background_principal.setLayer(jScrollPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        getContentPane().add(dp_background_principal, java.awt.BorderLayout.CENTER);

        pn_acciones.setBackground(new java.awt.Color(255, 204, 204));
        pn_acciones.setAlignmentX(0.0F);
        pn_acciones.setAlignmentY(0.0F);
        pn_acciones.setMinimumSize(new java.awt.Dimension(1372, 100));
        pn_acciones.setPreferredSize(new java.awt.Dimension(1372, 100));

        jButton1.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/pdf0.png"))); // NOI18N
        jButton1.setText("Generar PDF");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/search.png"))); // NOI18N
        jButton2.setText("Buscar");
        jButton2.setToolTipText("");

        javax.swing.GroupLayout pn_accionesLayout = new javax.swing.GroupLayout(pn_acciones);
        pn_acciones.setLayout(pn_accionesLayout);
        pn_accionesLayout.setHorizontalGroup(
            pn_accionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_accionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1251, Short.MAX_VALUE))
        );
        pn_accionesLayout.setVerticalGroup(
            pn_accionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_accionesLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(pn_accionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        getContentPane().add(pn_acciones, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_articuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_articuloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_articuloActionPerformed

    private void tf_nombre_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_nombre_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_nombre_usuarioActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
            NombreUsuario=tf_nombre_usuario.getText();Cantidad=tf_cantidad.getText();Autorizada=tf_autorizada.getText();
            Articulo=tf_articulo.getText();Fecha=tf_fecha.getText();
 
            JFileChooser file=new JFileChooser();
            file.showSaveDialog(this);
            File guarda =file.getSelectedFile();

            FileOutputStream archivo = new FileOutputStream(guarda+".pdf");


            /**/
            Document doc =new Document(PageSize.LETTER, 30, 30, 30, 30);
            PdfWriter writer= PdfWriter.getInstance(doc, archivo);
            doc.open();
            //doc.add(new Paragraph("Prueba",FontFactory.getFont(FontFactory.COURIER,10,Font.NORMAL,BaseColor.BLACK)));
            //Imagen de fondo
            Image imagen = Image.getInstance("img_vale_salida_almacen.jpg"); 
            imagen.scaleToFit(600, 1300);
            imagen.setAbsolutePosition(0, 0);
            doc.add(imagen);
            //Creación de objeto para formato de texto
            //BaseFont bf = BaseFont.createFont();
            BaseFont bf = BaseFont.createFont(BaseFont.COURIER, "", rootPaneCheckingEnabled);
            //Declaración de textos
            PdfContentByte txt_nombre_usuario = writer.getDirectContent();
            PdfContentByte txt_Cantidad = writer.getDirectContent();
            PdfContentByte txt_Autorizada = writer.getDirectContent();
            PdfContentByte txt_Articulo = writer.getDirectContent();
            PdfContentByte txt_Fecha = writer.getDirectContent();

            
            //Nombre usuario
            txt_nombre_usuario.saveState();
            txt_nombre_usuario.beginText();
            txt_nombre_usuario.setLineWidth(1.0f);
            txt_nombre_usuario.setRGBColorStroke(0x10, 0x10, 0x10);
            txt_nombre_usuario.setFontAndSize(bf, 9);
            txt_nombre_usuario.setTextMatrix(195, 670);
            txt_nombre_usuario.showText(NombreUsuario);
            txt_nombre_usuario.endText();
            txt_nombre_usuario.restoreState();
            //Cantidad
            txt_Cantidad.saveState();
            txt_Cantidad.beginText();
            txt_Cantidad.setLineWidth(1.0f);
            txt_Cantidad.setRGBColorStroke(0x10, 0x10, 0x10);
            txt_Cantidad.setFontAndSize(bf, 9);
            txt_Cantidad.setTextMatrix(200, 600);
            txt_Cantidad.showText(Cantidad);
            txt_Cantidad.endText();
            txt_Cantidad.restoreState();
            //Autorizada
            txt_Autorizada.saveState();
            txt_Autorizada.beginText();
            txt_Autorizada.setLineWidth(1.0f);
            txt_Autorizada.setRGBColorStroke(0x10, 0x10, 0x10);
            txt_Autorizada.setFontAndSize(bf, 9);
            txt_Autorizada.setTextMatrix(100, 586);
            txt_Autorizada.showText(Autorizada);
            txt_Autorizada.endText();
            txt_Autorizada.restoreState();
            //Articulo
            txt_Articulo.saveState();
            txt_Articulo.beginText();
            txt_Articulo.setLineWidth(1.0f);
            txt_Articulo.setRGBColorStroke(0x10, 0x10, 0x10);
            txt_Articulo.setFontAndSize(bf, 9);
            txt_Articulo.setTextMatrix(425, 614);
            txt_Articulo.showText(Articulo);
            txt_Articulo.endText();
            txt_Articulo.restoreState();
            //Fecha
            txt_Fecha.saveState();
            txt_Fecha.beginText();
            txt_Fecha.setLineWidth(1.0f);
            txt_Fecha.setRGBColorStroke(0x10, 0x10, 0x10);
            txt_Fecha.setFontAndSize(bf, 9);
            txt_Fecha.setTextMatrix(425, 900);
            txt_Fecha.showText(Fecha);
            txt_Fecha.endText();
            txt_Fecha.restoreState();

            
            JOptionPane.showMessageDialog(null,"El archivo se a guardado Exitosamente","Información",JOptionPane.INFORMATION_MESSAGE);
            doc.close();
        }catch(Exception e){}
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fr_Generacion_Vale_Resguardo_Bienes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fr_Generacion_Vale_Resguardo_Bienes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fr_Generacion_Vale_Resguardo_Bienes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fr_Generacion_Vale_Resguardo_Bienes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fr_Generacion_Vale_Salida_Almacen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dp_background_principal;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel lb_descripcion;
    private javax.swing.JLabel lb_marca;
    private javax.swing.JLabel lb_modelo;
    private javax.swing.JLabel lb_no_inventario;
    private javax.swing.JLabel lb_no_serie;
    private javax.swing.JPanel pb_principal;
    private javax.swing.JPanel pn_acciones;
    private javax.swing.JPanel pn_datos_bien_asignados;
    private javax.swing.JPanel pn_encabezado;
    private javax.swing.JTextField tf_articulo;
    private javax.swing.JTextField tf_autorizada;
    private javax.swing.JTextField tf_cantidad;
    private javax.swing.JTextField tf_fecha;
    private javax.swing.JTextField tf_nombre_usuario;
    // End of variables declaration//GEN-END:variables
}
