/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import clasesBackground.ImagenFondo;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Document;
import com.itextpdf.text.Font;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Image;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.BaseFont;
import com.itextpdf.text.pdf.PdfContentByte;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.File;
import java.io.FileOutputStream;
import java.io.FileWriter;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;

public class fr_Generacion_Vale_Recoleccion_Bienes extends javax.swing.JFrame {

    String Responsable,Cargo,Area,Tipo_de_uso,Municipio,Localidad,No_inventario,No_serie,Descripcion,Marca,Modelo,Color;
    public fr_Generacion_Vale_Recoleccion_Bienes() {
        initComponents();
        dp_background_principal.setBorder(new ImagenFondo());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pn_encabezado = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        dp_background_principal = new javax.swing.JDesktopPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        pb_principal = new javax.swing.JPanel();
        pn_datos_responsable = new javax.swing.JPanel();
        lb_responsable = new javax.swing.JLabel();
        lb_cargo = new javax.swing.JLabel();
        tf_responsable = new javax.swing.JTextField();
        tf_cargo = new javax.swing.JTextField();
        tf_area = new javax.swing.JTextField();
        lb_area = new javax.swing.JLabel();
        lb_tipo_de_uso = new javax.swing.JLabel();
        tf_tipo_de_uso = new javax.swing.JTextField();
        lb_municipio = new javax.swing.JLabel();
        tf_municipio = new javax.swing.JTextField();
        tf_localidad = new javax.swing.JTextField();
        lb_localidad = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        pn_datos_bien_asignados = new javax.swing.JPanel();
        lb_no_inventario = new javax.swing.JLabel();
        tf_no_inventario = new javax.swing.JTextField();
        tf_no_serie = new javax.swing.JTextField();
        lb_no_serie = new javax.swing.JLabel();
        lb_descripcion = new javax.swing.JLabel();
        tf_descripcion = new javax.swing.JTextField();
        lb_marca = new javax.swing.JLabel();
        tf_marca = new javax.swing.JTextField();
        lb_modelo = new javax.swing.JLabel();
        tf_modelo = new javax.swing.JTextField();
        lb_color = new javax.swing.JLabel();
        tf_color = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox();
        pn_acciones = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Generación de Vales de Resguardo de Bienes");
        setPreferredSize(new java.awt.Dimension(1372, 836));

        pn_encabezado.setBackground(new java.awt.Color(255, 204, 204));
        pn_encabezado.setAlignmentX(0.0F);
        pn_encabezado.setAlignmentY(0.0F);
        pn_encabezado.setPreferredSize(new java.awt.Dimension(1576, 150));
        pn_encabezado.setRequestFocusEnabled(false);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/IEE_logo-iloveimg-resized.png"))); // NOI18N

        javax.swing.GroupLayout pn_encabezadoLayout = new javax.swing.GroupLayout(pn_encabezado);
        pn_encabezado.setLayout(pn_encabezadoLayout);
        pn_encabezadoLayout.setHorizontalGroup(
            pn_encabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_encabezadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(1366, Short.MAX_VALUE))
        );
        pn_encabezadoLayout.setVerticalGroup(
            pn_encabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_encabezadoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addContainerGap())
        );

        getContentPane().add(pn_encabezado, java.awt.BorderLayout.NORTH);

        dp_background_principal.setBackground(new java.awt.Color(153, 153, 255));

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        pb_principal.setBackground(new java.awt.Color(255, 153, 152));

        pn_datos_responsable.setBackground(new java.awt.Color(255, 153, 153));
        pn_datos_responsable.setLayout(new java.awt.GridBagLayout());

        lb_responsable.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lb_responsable.setText("Responsable");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        pn_datos_responsable.add(lb_responsable, gridBagConstraints);

        lb_cargo.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lb_cargo.setText("Cargo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        pn_datos_responsable.add(lb_cargo, gridBagConstraints);

        tf_responsable.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        tf_responsable.setToolTipText("");
        tf_responsable.setMargin(new java.awt.Insets(0, 0, 0, 0));
        tf_responsable.setMinimumSize(new java.awt.Dimension(100, 30));
        tf_responsable.setPreferredSize(new java.awt.Dimension(200, 30));
        tf_responsable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_responsableActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        pn_datos_responsable.add(tf_responsable, gridBagConstraints);

        tf_cargo.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        tf_cargo.setMinimumSize(new java.awt.Dimension(100, 30));
        tf_cargo.setPreferredSize(new java.awt.Dimension(200, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        pn_datos_responsable.add(tf_cargo, gridBagConstraints);

        tf_area.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        tf_area.setMinimumSize(new java.awt.Dimension(100, 30));
        tf_area.setPreferredSize(new java.awt.Dimension(200, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        pn_datos_responsable.add(tf_area, gridBagConstraints);

        lb_area.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lb_area.setText("Area");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        pn_datos_responsable.add(lb_area, gridBagConstraints);

        lb_tipo_de_uso.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lb_tipo_de_uso.setText("Tipo de uso");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        pn_datos_responsable.add(lb_tipo_de_uso, gridBagConstraints);

        tf_tipo_de_uso.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        tf_tipo_de_uso.setMinimumSize(new java.awt.Dimension(100, 30));
        tf_tipo_de_uso.setPreferredSize(new java.awt.Dimension(200, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        pn_datos_responsable.add(tf_tipo_de_uso, gridBagConstraints);

        lb_municipio.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lb_municipio.setText("Municipio");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        pn_datos_responsable.add(lb_municipio, gridBagConstraints);

        tf_municipio.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        tf_municipio.setMinimumSize(new java.awt.Dimension(100, 30));
        tf_municipio.setPreferredSize(new java.awt.Dimension(200, 30));
        tf_municipio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_municipioActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        pn_datos_responsable.add(tf_municipio, gridBagConstraints);

        tf_localidad.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        tf_localidad.setMinimumSize(new java.awt.Dimension(100, 30));
        tf_localidad.setPreferredSize(new java.awt.Dimension(200, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        pn_datos_responsable.add(tf_localidad, gridBagConstraints);

        lb_localidad.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lb_localidad.setText("Localidad");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        pn_datos_responsable.add(lb_localidad, gridBagConstraints);

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setText("Datos del responsable");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        pn_datos_responsable.add(jLabel1, gridBagConstraints);

        pn_datos_bien_asignados.setBackground(new java.awt.Color(255, 153, 153));
        pn_datos_bien_asignados.setLayout(new java.awt.GridBagLayout());

        lb_no_inventario.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lb_no_inventario.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lb_no_inventario.setText("No. Inventario");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        pn_datos_bien_asignados.add(lb_no_inventario, gridBagConstraints);

        tf_no_inventario.setMinimumSize(new java.awt.Dimension(150, 30));
        tf_no_inventario.setPreferredSize(new java.awt.Dimension(150, 30));
        tf_no_inventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_no_inventarioActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 271;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        pn_datos_bien_asignados.add(tf_no_inventario, gridBagConstraints);

        tf_no_serie.setMinimumSize(new java.awt.Dimension(150, 30));
        tf_no_serie.setPreferredSize(new java.awt.Dimension(150, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 271;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        pn_datos_bien_asignados.add(tf_no_serie, gridBagConstraints);

        lb_no_serie.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lb_no_serie.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lb_no_serie.setText("No. Serie");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        pn_datos_bien_asignados.add(lb_no_serie, gridBagConstraints);

        lb_descripcion.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lb_descripcion.setText("Descripción");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        pn_datos_bien_asignados.add(lb_descripcion, gridBagConstraints);

        tf_descripcion.setMinimumSize(new java.awt.Dimension(150, 30));
        tf_descripcion.setPreferredSize(new java.awt.Dimension(150, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 271;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        pn_datos_bien_asignados.add(tf_descripcion, gridBagConstraints);

        lb_marca.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lb_marca.setText("Marca");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        pn_datos_bien_asignados.add(lb_marca, gridBagConstraints);

        tf_marca.setMinimumSize(new java.awt.Dimension(150, 30));
        tf_marca.setPreferredSize(new java.awt.Dimension(150, 30));
        tf_marca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_marcaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 271;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        pn_datos_bien_asignados.add(tf_marca, gridBagConstraints);

        lb_modelo.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lb_modelo.setText("Modelo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        pn_datos_bien_asignados.add(lb_modelo, gridBagConstraints);

        tf_modelo.setMinimumSize(new java.awt.Dimension(150, 30));
        tf_modelo.setPreferredSize(new java.awt.Dimension(150, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 271;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        pn_datos_bien_asignados.add(tf_modelo, gridBagConstraints);

        lb_color.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lb_color.setText("Color");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        pn_datos_bien_asignados.add(lb_color, gridBagConstraints);

        tf_color.setMinimumSize(new java.awt.Dimension(150, 30));
        tf_color.setPreferredSize(new java.awt.Dimension(150, 30));
        tf_color.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_colorActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 271;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        pn_datos_bien_asignados.add(tf_color, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel3.setText("Relación de mobiliario y equipo de cómputo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        pn_datos_bien_asignados.add(jLabel3, gridBagConstraints);

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Responsable", "Cargo", "Area", "Tipo de uso", "Municipio", "Localidad" }));
        jComboBox1.setMinimumSize(new java.awt.Dimension(56, 30));
        jComboBox1.setPreferredSize(new java.awt.Dimension(56, 30));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jTextField1.setPreferredSize(new java.awt.Dimension(59, 30));

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel2.setText("Criterio:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(107, 107, 107)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(21, 21, 21))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 153, 153));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(jTable2);

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel4.setText("Criterio:");

        jTextField2.setPreferredSize(new java.awt.Dimension(6, 30));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "No. Inventario", "No. Serie", "Descripción", "Marca", "Modelo", "Color" }));
        jComboBox2.setPreferredSize(new java.awt.Dimension(56, 30));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pb_principalLayout = new javax.swing.GroupLayout(pb_principal);
        pb_principal.setLayout(pb_principalLayout);
        pb_principalLayout.setHorizontalGroup(
            pb_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pb_principalLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(pb_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pn_datos_bien_asignados, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pn_datos_responsable, javax.swing.GroupLayout.DEFAULT_SIZE, 634, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(145, 145, 145))
        );
        pb_principalLayout.setVerticalGroup(
            pb_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pb_principalLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(pn_datos_responsable, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pn_datos_bien_asignados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jScrollPane2.setViewportView(pb_principal);

        javax.swing.GroupLayout dp_background_principalLayout = new javax.swing.GroupLayout(dp_background_principal);
        dp_background_principal.setLayout(dp_background_principalLayout);
        dp_background_principalLayout.setHorizontalGroup(
            dp_background_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dp_background_principalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 762, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(804, Short.MAX_VALUE))
        );
        dp_background_principalLayout.setVerticalGroup(
            dp_background_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dp_background_principalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 602, Short.MAX_VALUE)
                .addContainerGap())
        );
        dp_background_principal.setLayer(jScrollPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        getContentPane().add(dp_background_principal, java.awt.BorderLayout.CENTER);

        pn_acciones.setBackground(new java.awt.Color(255, 204, 204));
        pn_acciones.setAlignmentX(0.0F);
        pn_acciones.setAlignmentY(0.0F);
        pn_acciones.setMinimumSize(new java.awt.Dimension(1372, 100));
        pn_acciones.setPreferredSize(new java.awt.Dimension(1372, 100));

        jButton1.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/pdf0.png"))); // NOI18N
        jButton1.setText("Generar PDF");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/search.png"))); // NOI18N
        jButton2.setText("Buscar");
        jButton2.setToolTipText("");

        javax.swing.GroupLayout pn_accionesLayout = new javax.swing.GroupLayout(pn_acciones);
        pn_acciones.setLayout(pn_accionesLayout);
        pn_accionesLayout.setHorizontalGroup(
            pn_accionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_accionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1251, Short.MAX_VALUE))
        );
        pn_accionesLayout.setVerticalGroup(
            pn_accionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_accionesLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(pn_accionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        getContentPane().add(pn_acciones, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_municipioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_municipioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_municipioActionPerformed

    private void tf_marcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_marcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_marcaActionPerformed

    private void tf_no_inventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_no_inventarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_no_inventarioActionPerformed

    private void tf_responsableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_responsableActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_responsableActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void tf_colorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_colorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_colorActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
            Responsable=tf_responsable.getText();Cargo=tf_cargo.getText();Area=tf_area.getText();Tipo_de_uso=tf_tipo_de_uso.getText();
            Municipio=tf_municipio.getText();Localidad=tf_localidad.getText();No_inventario=tf_no_inventario.getText();
            No_serie=tf_no_serie.getText();Descripcion=tf_descripcion.getText();Marca=tf_marca.getText();Modelo=tf_modelo.getText();Color=tf_color.getText();
 
            JFileChooser file=new JFileChooser();
            file.showSaveDialog(this);
            File guarda =file.getSelectedFile();

            FileOutputStream archivo = new FileOutputStream(guarda+".pdf");

            
            
            
            /**/
            Document doc =new Document(PageSize.LETTER, 30, 30, 30, 30);
            PdfWriter writer= PdfWriter.getInstance(doc, archivo);
            doc.open();
            //doc.add(new Paragraph("Prueba",FontFactory.getFont(FontFactory.COURIER,10,Font.NORMAL,BaseColor.BLACK)));
            //Imagen de fondo
            Image imagen = Image.getInstance("img_vale_recoleccion_bienes.jpg"); 
            imagen.scaleToFit(600, 1300);
            imagen.setAbsolutePosition(0, 0);
            doc.add(imagen);
            //Creación de objeto para formato de texto
            //BaseFont bf = BaseFont.createFont();
            BaseFont bf = BaseFont.createFont(BaseFont.COURIER, "", rootPaneCheckingEnabled);
            //Declaración de textos
            PdfContentByte txt_Responsable = writer.getDirectContent();
            PdfContentByte txt_Cargo = writer.getDirectContent();
            PdfContentByte txt_Area = writer.getDirectContent();
            PdfContentByte txt_Tipo_de_uso = writer.getDirectContent();
            PdfContentByte txt_Municipio = writer.getDirectContent();
            PdfContentByte txt_Localidad = writer.getDirectContent();
            
            //Responsable
            txt_Responsable.saveState();
            txt_Responsable.beginText();
            txt_Responsable.setLineWidth(1.0f);
            txt_Responsable.setRGBColorStroke(0x10, 0x10, 0x10);
            txt_Responsable.setFontAndSize(bf, 9);
            txt_Responsable.setTextMatrix(100, 614);
            txt_Responsable.showText(Responsable);
            txt_Responsable.endText();
            txt_Responsable.restoreState();
            //Cargo
            txt_Cargo.saveState();
            txt_Cargo.beginText();
            txt_Cargo.setLineWidth(1.0f);
            txt_Cargo.setRGBColorStroke(0x10, 0x10, 0x10);
            txt_Cargo.setFontAndSize(bf, 9);
            txt_Cargo.setTextMatrix(100, 600);
            txt_Cargo.showText(Cargo);
            txt_Cargo.endText();
            txt_Cargo.restoreState();
            //Area
            txt_Area.saveState();
            txt_Area.beginText();
            txt_Area.setLineWidth(1.0f);
            txt_Area.setRGBColorStroke(0x10, 0x10, 0x10);
            txt_Area.setFontAndSize(bf, 9);
            txt_Area.setTextMatrix(100, 586);
            txt_Area.showText(Area);
            txt_Area.endText();
            txt_Area.restoreState();
            //Tipo_de_uso
            txt_Tipo_de_uso.saveState();
            txt_Tipo_de_uso.beginText();
            txt_Tipo_de_uso.setLineWidth(1.0f);
            txt_Tipo_de_uso.setRGBColorStroke(0x10, 0x10, 0x10);
            txt_Tipo_de_uso.setFontAndSize(bf, 9);
            txt_Tipo_de_uso.setTextMatrix(425, 614);
            txt_Tipo_de_uso.showText(Tipo_de_uso);
            txt_Tipo_de_uso.endText();
            txt_Tipo_de_uso.restoreState();
            //Municipio
            txt_Municipio.saveState();
            txt_Municipio.beginText();
            txt_Municipio.setLineWidth(1.0f);
            txt_Municipio.setRGBColorStroke(0x10, 0x10, 0x10);
            txt_Municipio.setFontAndSize(bf, 9);
            txt_Municipio.setTextMatrix(425, 600);
            txt_Municipio.showText(Municipio);
            txt_Municipio.endText();
            txt_Municipio.restoreState();
            //Localidad
            txt_Localidad.saveState();
            txt_Localidad.beginText();
            txt_Localidad.setLineWidth(1.0f);
            txt_Localidad.setRGBColorStroke(0x10, 0x10, 0x10);
            txt_Localidad.setFontAndSize(bf, 9);
            txt_Localidad.setTextMatrix(425, 586);
            txt_Localidad.showText(Localidad);
            txt_Localidad.endText();
            txt_Localidad.restoreState();
            
            JOptionPane.showMessageDialog(null,"El archivo se a guardado Exitosamente","Información",JOptionPane.INFORMATION_MESSAGE);
            doc.close();
        }catch(Exception e){}
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fr_Generacion_Vale_Resguardo_Bienes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fr_Generacion_Vale_Resguardo_Bienes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fr_Generacion_Vale_Resguardo_Bienes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fr_Generacion_Vale_Resguardo_Bienes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fr_Generacion_Vale_Recoleccion_Bienes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dp_background_principal;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel lb_area;
    private javax.swing.JLabel lb_cargo;
    private javax.swing.JLabel lb_color;
    private javax.swing.JLabel lb_descripcion;
    private javax.swing.JLabel lb_localidad;
    private javax.swing.JLabel lb_marca;
    private javax.swing.JLabel lb_modelo;
    private javax.swing.JLabel lb_municipio;
    private javax.swing.JLabel lb_no_inventario;
    private javax.swing.JLabel lb_no_serie;
    private javax.swing.JLabel lb_responsable;
    private javax.swing.JLabel lb_tipo_de_uso;
    private javax.swing.JPanel pb_principal;
    private javax.swing.JPanel pn_acciones;
    private javax.swing.JPanel pn_datos_bien_asignados;
    private javax.swing.JPanel pn_datos_responsable;
    private javax.swing.JPanel pn_encabezado;
    private javax.swing.JTextField tf_area;
    private javax.swing.JTextField tf_cargo;
    private javax.swing.JTextField tf_color;
    private javax.swing.JTextField tf_descripcion;
    private javax.swing.JTextField tf_localidad;
    private javax.swing.JTextField tf_marca;
    private javax.swing.JTextField tf_modelo;
    private javax.swing.JTextField tf_municipio;
    private javax.swing.JTextField tf_no_inventario;
    private javax.swing.JTextField tf_no_serie;
    private javax.swing.JTextField tf_responsable;
    private javax.swing.JTextField tf_tipo_de_uso;
    // End of variables declaration//GEN-END:variables
}
