/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;
//Clases importadas
import Clases.Conexion;
import Clases.ManagerLogin;

import com.alee.laf.WebLookAndFeel;
import com.sun.java.swing.plaf.motif.MotifLookAndFeel;
import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;


/**
 *
 * @author oscar
 */
public class Login extends javax.swing.JFrame {
    //Variables de las clases
    private final Conexion check_con;
    private final ManagerLogin manager;
    //Variables globales de la interfaz
    private String password;
    private String user;
    /**
     * Creates new form LogIn
     */
    public Login(){
        super();
        
        initComponents();
        //Asignacion de memoria a objetos
        manager = new ManagerLogin();
        check_con = new Conexion();
        
        this.setLocationRelativeTo(null);
        //centrar texto
        campoUsuario.setHorizontalAlignment (campoUsuario.CENTER);
        campoContraseña.setHorizontalAlignment (campoContraseña.CENTER);
        setBackground(new Color(0, 255, 0, 0));
        jPanel1.setBackground(new Color(0, 255, 0, 0));
        setIconImage(new ImageIcon(getClass().getResource("/Iconos/IEE.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        campoUsuario = new javax.swing.JTextField();
        campoContraseña = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 204, 0));
        jPanel1.setLayout(null);

        campoUsuario.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jPanel1.add(campoUsuario);
        campoUsuario.setBounds(220, 110, 200, 30);

        campoContraseña.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        campoContraseña.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campoContraseñaKeyReleased(evt);
            }
        });
        jPanel1.add(campoContraseña);
        campoContraseña.setBounds(220, 160, 200, 28);

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/banerLogin.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 20, 530, 80);

        jButton1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/aceptar.png"))); // NOI18N
        jButton1.setText("  Ingresar");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(300, 220, 120, 30);

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel4.setText("Contraseña :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(110, 160, 110, 20);

        jButton2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/cancelar.png"))); // NOI18N
        jButton2.setText("  Cancelar");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(160, 220, 120, 30);

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel5.setText("Usuario :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(140, 120, 80, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondoLogin.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 580, 300);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         // TODO add your handling code here:
        if(check_con.hayConexion()) {
            if (iniciarSesion()) {
                Principal ob = new Principal();
                this.hide();
                ob.setVisible(true);
            }
        } else {
            JOptionPane.showMessageDialog(this, "NO HAY CONEXION CON LA BD");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void campoContraseñaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoContraseñaKeyReleased
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            System.exit(0);

        } else if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (iniciarSesion()) {
                Principal ob = new Principal();
                this.hide();
                //ob.setIDUsuario(id);
                ob.setVisible(true);
            }

        }
    }//GEN-LAST:event_campoContraseñaKeyReleased
   
    //Métodos
    public boolean validar(){
        boolean res = false;
        if(campoUsuario.getText().isEmpty() || campoContraseña.getText().isEmpty()){
            res = true;
        }
        return res;
    }
    
    private boolean validarID() {

        if (campoUsuario.getText().equals("")) {
            return false; //si no ingreso ningun numero
        }
        return true;

    }//validarID
    
    private boolean validarPassword() {
        password = campoContraseña.getText();
        if (password.isEmpty()) {
            return false; //se retorna false si no ingreso contraseÃ±a
        }
        return true;
    }//validarPasswo
    
    private boolean iniciarSesion() {
        if (validarID()) {
            if (validarPassword()) {
                user = campoUsuario.getText();
                int resultado = manager.iniciarSesion(user, password); //obtenemos de la base de datos informacion sobre el si se concreto el login
                if (resultado == 0) {
                    JOptionPane.showMessageDialog(this, "El usuario no existe!","Información",JOptionPane.INFORMATION_MESSAGE);
                    campoUsuario.setText("");
                    campoContraseña.setText("");
                    campoUsuario.requestFocus();
                    return false;
                }//
                //NO ES NECESARIO-----------------------------------------------------------------
                if (resultado == 2) {

                    JOptionPane.showMessageDialog(this, "El usuario no es administrador");
                    campoContraseña.setText("");
                    campoContraseña.requestFocus();
                    return false;
                }//

                if (resultado == 1) {
                    JOptionPane.showMessageDialog(this, "Contraseña incorrecta!","Información",JOptionPane.WARNING_MESSAGE);
                    campoContraseña.setText("");
                    campoContraseña.requestFocus();
                    return false;
                }//

                if (resultado == 3) {
                    return true;
                }//

            } else {
                JOptionPane.showMessageDialog(this, "Ingrese una Contraseña");

            }//
        } else {
            JOptionPane.showMessageDialog(this, "Ingrese un usuario valido");

        }//

        return false;
    }//Iniciar Sesion
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws UnsupportedLookAndFeelException{
      UIManager.setLookAndFeel(new WebLookAndFeel());
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                    new Login().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField campoContraseña;
    private javax.swing.JTextField campoUsuario;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
