/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import com.alee.laf.WebLookAndFeel;
//import com.sun.java.swing.plaf.motif.MotifLookAndFeel;
import java.awt.Color;
import javax.swing.ImageIcon;
//import javax.swing.UIManager;
//import javax.swing.UnsupportedLookAndFeelException;

//Importamos los TDA que haraán la conexión con la BD
import Clases.Conexion;
import Clases.ManagerLogin;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author oscar
 */
public class Login extends javax.swing.JFrame {
    private String password;
    private String user;
    private Conexion check_con;
    private ManagerLogin manager;
    /**
     * Creates new form LogIn
     */
    public Login(){
        super();
        
        initComponents();
        //asignacion de memoria a objetos
        
        this.setLocationRelativeTo(null);
        //centrar texto
        tf_campoUsuario.setHorizontalAlignment (tf_campoUsuario.CENTER);
        tf_campoContraseña.setHorizontalAlignment (tf_campoContraseña.CENTER);
        setBackground(new Color(0, 255, 0, 0));
        pn_principal_Login.setBackground(new Color(0, 255, 0, 0));
        setIconImage(new ImageIcon(getClass().getResource("/Iconos/IEE.png")).getImage());
        
        //Asignación de memoria a objetos
        manager = new ManagerLogin();
        check_con = new Conexion();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_principal_Login = new javax.swing.JPanel();
        tf_campoUsuario = new javax.swing.JTextField();
        tf_campoContraseña = new javax.swing.JPasswordField();
        lb_logoIEEN_Login = new javax.swing.JLabel();
        btn_ingresar = new javax.swing.JButton();
        lb_contraseña = new javax.swing.JLabel();
        btn_cancelar = new javax.swing.JButton();
        lb_usuario = new javax.swing.JLabel();
        lb_background_Login = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        pn_principal_Login.setBackground(new java.awt.Color(255, 204, 0));
        pn_principal_Login.setLayout(null);

        tf_campoUsuario.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        tf_campoUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_campoUsuarioKeyReleased(evt);
            }
        });
        pn_principal_Login.add(tf_campoUsuario);
        tf_campoUsuario.setBounds(220, 110, 200, 30);

        tf_campoContraseña.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        tf_campoContraseña.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_campoContraseñaKeyReleased(evt);
            }
        });
        pn_principal_Login.add(tf_campoContraseña);
        tf_campoContraseña.setBounds(220, 160, 200, 28);

        lb_logoIEEN_Login.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        lb_logoIEEN_Login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/banerLogin.png"))); // NOI18N
        pn_principal_Login.add(lb_logoIEEN_Login);
        lb_logoIEEN_Login.setBounds(20, 20, 530, 80);

        btn_ingresar.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        btn_ingresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/aceptar.png"))); // NOI18N
        btn_ingresar.setText("  Ingresar");
        btn_ingresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ingresarActionPerformed(evt);
            }
        });
        pn_principal_Login.add(btn_ingresar);
        btn_ingresar.setBounds(300, 220, 120, 30);

        lb_contraseña.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lb_contraseña.setText("Contraseña :");
        pn_principal_Login.add(lb_contraseña);
        lb_contraseña.setBounds(110, 160, 110, 20);

        btn_cancelar.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        btn_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/cancelar.png"))); // NOI18N
        btn_cancelar.setText("  Cancelar");
        btn_cancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });
        pn_principal_Login.add(btn_cancelar);
        btn_cancelar.setBounds(160, 220, 120, 30);

        lb_usuario.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lb_usuario.setText("Usuario :");
        pn_principal_Login.add(lb_usuario);
        lb_usuario.setBounds(140, 120, 80, 20);

        lb_background_Login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondoLogin.png"))); // NOI18N
        pn_principal_Login.add(lb_background_Login);
        lb_background_Login.setBounds(0, 0, 580, 300);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_principal_Login, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_principal_Login, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void btn_ingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ingresarActionPerformed
         // TODO add your handling code here:
         if (check_con.hayConexion()) {
            if (iniciarSesion()) {
                Principal ob = new Principal();
                this.hide();
                //ob.setIDUsuario(id);
                ob.setVisible(true);
            }
        } else {
            JOptionPane.showMessageDialog(this, "NO HAY CONEXION CON LA BD");
        }
    }//GEN-LAST:event_btn_ingresarActionPerformed

    private void tf_campoUsuarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_campoUsuarioKeyReleased
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            System.exit(0);
        }
    }//GEN-LAST:event_tf_campoUsuarioKeyReleased

    private void tf_campoContraseñaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_campoContraseñaKeyReleased
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            System.exit(0);

        } else if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (iniciarSesion()) {
                Principal ob = new Principal();
                this.hide();
                //ob.setIDUsuario(id);
                ob.setVisible(true);
            }

        }
    }//GEN-LAST:event_tf_campoContraseñaKeyReleased
   
    public boolean validar(){
        boolean res = false;
        if(tf_campoUsuario.getText().isEmpty() || tf_campoContraseña.getText().isEmpty()){
            res = true;
        }
        return res;
    }
    
    private boolean validarID() {

        if (tf_campoUsuario.getText().equals("")) {
            return false; //si no ingreso ningun numero
        }
        return true;

    }//validarID
    
    private boolean validarPassword() {
        password = tf_campoContraseña.getText();
        if (password.isEmpty()) {
            return false; //se retorna false si no ingreso contraseÃ±a
        }
        return true;
    }//validarPasswo
    
    private boolean iniciarSesion() {
        if (validarID()) {
            if (validarPassword()) {
                user = tf_campoUsuario.getText();
                int resultado = manager.iniciarSesion(user, password); //obtenemos de la base de datos informacion sobre el si se concreto el login
                if (resultado == 0) {
                    JOptionPane.showMessageDialog(this, "El usuario no existe!","Información",JOptionPane.INFORMATION_MESSAGE);
                    tf_campoUsuario.setText("");
                    tf_campoContraseña.setText("");
                    tf_campoUsuario.requestFocus();
                    return false;
                }//
                //NO ES NECESARIO-----------------------------------------------------------------
                if (resultado == 2) {

                    JOptionPane.showMessageDialog(this, "El usuario no es administrador");
                    tf_campoContraseña.setText("");
                    tf_campoContraseña.requestFocus();
                    return false;
                }//

                if (resultado == 1) {
                    JOptionPane.showMessageDialog(this, "Contraseña incorrecta!","Información",JOptionPane.WARNING_MESSAGE);
                    tf_campoContraseña.setText("");
                    tf_campoContraseña.requestFocus();
                    return false;
                }//

                if (resultado == 3) {
                    return true;
                }//

            } else {
                JOptionPane.showMessageDialog(this, "Ingrese una Contraseña");

            }//
        } else {
            JOptionPane.showMessageDialog(this, "Ingrese un usuario valido");

        }//

        return false;
    }//Iniciar Sesion
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) /*throws UnsupportedLookAndFeelException*/{
      //UIManager.setLookAndFeel(new WebLookAndFeel());
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                    new Login().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_ingresar;
    private javax.swing.JLabel lb_background_Login;
    private javax.swing.JLabel lb_contraseña;
    private javax.swing.JLabel lb_logoIEEN_Login;
    private javax.swing.JLabel lb_usuario;
    private javax.swing.JPanel pn_principal_Login;
    private javax.swing.JPasswordField tf_campoContraseña;
    private javax.swing.JTextField tf_campoUsuario;
    // End of variables declaration//GEN-END:variables
}
